repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        name: Ruff Linter
        args: [--no-fix]

      - id: ruff-format
        name: Ruff Formatter
        args: [--check]